service: lesli-builder
image: leslitech/lesli-builder

servers:
  web:
    - 3.87.145.0

proxy:
  ssl: true
  host: demo.lesli.dev
  app_port: 3000
  healthcheck:
    path: /up

registry:
  server: ghcr.io
  username: leslitech
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: ubuntu
  keys:


builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
